easy_admin:
    site_name: 'GWITH Admin'
    user:
        display_name: true
        display_avatar: false
    entities:
        # List the entity class name you want to manage
        - App\Entity\Action
        - App\Entity\ActionType
        - App\Entity\AppUser
        - App\Entity\Avatar
        - App\Entity\Event
        - App\Entity\EventType
        - App\Entity\Place
        - App\Entity\PlaceType
        - App\Entity\Rating
        - App\Entity\Scene
        - App\Entity\Story
        - App\Entity\StoryCategory
        - App\Entity\Transition

